#import "../module/module.typ": *
#show: module

#tag("symmetric-space-locally") := under geodesic coordinate, inversion $-𝟙$ is isometry. equivalently, $∇ R = 0$ 

*Example* quadratic manifold, simple-Lie-group and related symmetric-space

constant-sectional-curvature ==> symmetric-space

simple-Lie-group := Lie-algebra & Lie-bracket cannot decompose 

Killing form := $g(X,Y) := ± tr [X,[Y,]] = ± tr("ad" X "ad" Y)$ for $X,Y$ in the tangent space at $𝟙$

Then define the metric at $𝟙$ to be the metric at other places generated by the action, and it is bi-invariant i.e. both forms of group action give the same metric

Such a definition makes the group action an isometry of the Killing-form

Killing-form can also be defined for non-simple-Lie-groups

*Question* Motivation for the definition of Killing-form?

simple-Lie-group <==> Killing-form is non-degenerate

The Killing-form of simple-Lie-group and its symmetric-space is Einstein-metric 

#let L = c-diff($L$)

_Proof_ for the case of simple-Lie-group
#indent[
  - $g([X,X'],X'') + g (X',[X,X'']) = 0$ for Lie algebra $X,X',X''$
  
  _Proof_
  #indent[
    Lie-algebra ==> δ-isometry ==> for δ-group-action $X$, $∂_X g = 0$ 

    Because the Killing-form is the metric generated by the group action, the Lie-derivative is zero $#L _X g = 0$

    For fields generated by $X,X',X''$
    $
      0 &= #L _X (g (X',X'')) \
      &= (∂_X g) (X',X'') \
        &quad - (g(#L _X X',X'') + g(X',#L _X X'')) \
      &= g([X,X'],X'') + g (X',[X,X''])
    $
  ]
  - geodesic-derivative $∇ = 1/2 [,]$. _Proof_ see below

  - curvature $[∇_i,∇_i'] j = - 1/4 [[i,i'],j]$

  - $∇ R = 0$. hence symmetric-space-locally

  - curvature $g([∇_i,∇_i']j,j') = - 1/4 g([i,i'],[j,j'])$

  - sectional-curvature for orthonormal $- 1/4 |[X,Y]|^2$

  - Ricci-curvature $"Ric"(X,Y) = 1/4 tr [X,[Y,]] = ± 1/4 g$. hence Einstein-metric

  - scalar-curvature $"scal" = ± 1/4 dim$
]
*Prop* $∇_X Y = 1/2 [X,Y]$ at $𝟙$, similarly for fields generated by $X,Y$ (bi-invariant)

_Proof_ 
#indent[
  *Prop* $∇_X X = 0$ 
  
  This gives $∇_X Y + ∇_Y X = 0$
  
  with $∇_X Y - ∇_Y X = [X,Y]$, this gives $∇ = 1/2 [,]$

  _Proof_ of $∇_X X = 0$
  #indent[
    need $g(Y, ∇_X X) = 0$

    Since group action generates $g,X',X''$, $g(X',X'')("at" p) equiv g(X',X'')("at" 𝟙)$ constant value ==> $∂ g(X',X'') = 0$
    
    $0 = ∂_X (g(X',X'')) = g(∇_X X', X'') + g(X', ∇_X X'')$

    need $g(∇_X Y, X) = 0$

    $∇_X Y - ∇_Y X = [X,Y]$
    
    $g([X,Y],X) = - g (Y, [X,X]) = 0$

    need $g(∇_Y X, X) = 0$

    by $0 = ∂_Y (g(X, X))$

  *Question* any more intuitive proof?
  ]
]
*Prop* for simple-Lie-group
#indent[
  Integral curves of bi-invariant vector fields generated by Lie algebra are Killing-form geodesics, because
    - Geodesics can be written as $∇_vel(x) vel(x) = 0$
    - Assume $vel(x)$ is an integral curve of $X$, $vel(x)(t) = X(x(t))$
    - $∇_X X = 0$
]
Quadratic form manifold. Symmetric group of $ℝ^(p,q)$ is $SO(p,q)$

  - orbit type $|x|^2 = 1$ or $ℚ^(p,q)(1)$ 
    - induced metric signature $(p-1,q)$ (normal vector $|x|^2 = 1 > 0$)
    - isotropy-group $SO(p-1,q)$ 
    - quotient $(SO(p,q))/(SO(p-1,q)) = ℚ^(p,q)(1)$
    - isometry of $ℚ^(p,q)(1)$ is $SO(p,q)$ (isometry assumed to preserve direction)

  - orbit type $|x|^2 = -1$ or $ℚ^(p,q)(-1)$
    - induced metric signature $(p,q-1)$ (normal vector $|x|^2 = -1 < 0$)
    - isotropy-group $SO(p,q-1)$
    - quotient $(SO(p,q))/(SO(p,q-1)) = ℚ^(p,q)(-1)$
    - isometry of $ℚ^(p,q)(-1)$ is $SO(p,q)$

$ℚ^(p,q)(± 1) = ℚ^(q,p)(∓ 1)$

*Example* 

  - $(0,n)$ spatial manifold has $ℚ^(1,n)(1) = ℍ𝕪^n = SO(1,n)/SO(n),ℚ^(0,n+1)(-1) = 𝕊^n = SO(n+1)/SO(n)$

  - $(1,n-1)$ spacetime quadratic manifold has $ℚ^(2,n-1)(1) = SO(2,n-1)/SO(1,n-1)$ and hyperboloid of one sheet $ℚ^(1,n)(-1) = SO(1,n)/SO(1,n-1)$ 

#let g = c-Lie-algebra("g")
#let h = c-Lie-algebra("h")

Examples of quadratic manifolds with this property

simple-Lie-group $G$, simple-Lie-group isotropy $H$, orbit $G/H$

Lie-algebra has orthogonal decomposition $#g = #h ⊕ #g/#h$, not Lie bracket decomposition

$#h$ is the Lie-algebra of $H$, $#g/#h = #h^⟂$ is the orthogonal complement 

$exp$ gives the coordinates of $G,H,G/H$

The Killing-form of $#g$ derives the Killing-form of $#h$ and the Einstein metric of $#g/#h$

- $[#h,#h] ⊆ #h$

- $[#h,#g/#h] ⊆ #g/#h$

- $[#g/#h,#g/#h] ⊆ #h$