#import "@preview/shiroa:0.2.3": *

#show: book

#book-meta(
  title: "note-math",
  repository: "https://github.com/ecbc0/note-math",
  summary: [
    #prefix-chapter("item_en/notice_en.typ")[notice]
    = English
    = logic-topic
      - #chapter("item_en/logic_en.typ")[logic]
      - #chapter("item_en/basic_en.typ")[basic]
      - #chapter("item_en/map_en.typ")[map]
      - #chapter("item_en/order_en.typ")[order]
      - #chapter("item_en/combinatorics_en.typ")[combinatorics]
    = calculus
      - #chapter("item_en/real-numbers_en.typ")[real-numbers]
      - #chapter("item_en/limit-sequence_en.typ")[limit-sequence]
      - #chapter("item_en/division-algebra_en.typ")[division-algebra]
      - #chapter("item_en/Euclidean-space_en.typ")[Euclidean-space]
      - #chapter("item_en/Minkowski-space_en.typ")[Minkowski-space]
      - #chapter("item_en/polynomial_en.typ")[polynomial]
      - #chapter("item_en/analytic-Euclidean_en.typ")[analytic-Euclidean]
      - #chapter("item_en/analytic-Minkowski_en.typ")[analytic-Minkowski]
      - #chapter("item_en/analytic-struct-operation_en.typ")[analytic-struct-operation]
      - #chapter("item_en/ordinary-differential-equation_en.typ")[ordinary-differential-equation]
      - #chapter("item_en/volume_en.typ")[volume]
      - #chapter("item_en/integral_en.typ")[integral]
      - #chapter("item_en/divergence_en.typ")[divergence]
      - #chapter("item_en/limit-net_en.typ")[limit-net]
      - #chapter("item_en/topology_en.typ")[topology]
      - #chapter("item_en/compact_en.typ")[compact]
      - #chapter("item_en/connected_en.typ")[connected]
      - #chapter("item_en/topology-struct-operation_en.typ")[topology-struct-operation]
      - #chapter("item_en/exponential_en.typ")[exponential]
      - #chapter("item_en/angle_en.typ")[angle]
    = geometry
      - #chapter("item_en/manifold_en.typ")[manifold]
      - #chapter("item_en/metric_en.typ")[metric]
      - #chapter("item_en/metric-connection_en.typ")[metric-connection]
      - #chapter("item_en/geodesic-derivative_en.typ")[geodesic-derivative]
      - #chapter("item_en/curvature-of-metric_en.typ")[curvature-of-metric]
      - #chapter("item_en/Einstein-metric_en.typ")[Einstein-metric]
      - #chapter("item_en/constant-sectional-curvature_en.typ")[constant-sectional-curvature]
      - #chapter("item_en/simple-symmetric-space_en.typ")[simple-symmetric-space]
      - #chapter("item_en/principal-bundle_en.typ")[principal-bundle]
      - #chapter("item_en/group_en.typ")[group]
      - #chapter("item_en/stereographic-projection_en.typ")[stereographic-projection]
      - #chapter("item_en/Hopf-bundle_en.typ")[Hopf-bundle]
    = field-theory
      - #chapter("item_en/point-particle-non-relativity_en.typ")[point-particle-non-relativity]
      - #chapter("item_en/point-particle-relativity_en.typ")[point-particle-relativity]
      - #chapter("item_en/scalar-field_en.typ")[scalar-field]
      - #chapter("item_en/scalar-field-current_en.typ")[scalar-field-current]
      - #chapter("item_en/scalar-field-non-relativity_en.typ")[scalar-field-non-relativity]
      - #chapter("item_en/projective-lightcone_en.typ")[projective-lightcone]
      - #chapter("item_en/spacetime-momentum-spinor-representation_en.typ")[spacetime-momentum-spinor-representation]
      - #chapter("item_en/Lorentz-group_en.typ")[Lorentz-group]
      - #chapter("item_en/spinor-field_en.typ")[spinor-field]
      - #chapter("item_en/spinor-field-current_en.typ")[spinor-field-current]
      - #chapter("item_en/electromagnetic-field_en.typ")[electromagnetic-field]
      - #chapter("item_en/Laplacian-of-tensor-field_en.typ")[Laplacian-of-tensor-field]
      - #chapter("item_en/Einstein-metric_en.typ")[Einstein-metric]
      - #chapter("item_en/interaction_en.typ")[interaction]
      - #chapter("item_en/harmonic-oscillator-quantization_en.typ")[harmonic-oscillator-quantization]
      - #chapter("item_en/spinor-field-misc_en.typ")[spinor-field-misc]
    - #chapter("reference.typ")[reference]
    = 中文
    #chapter("item/notice.typ")[notice]
    = 逻辑
      - #chapter("item/logic.typ")[逻辑]
      - #chapter("item/basic.typ")[基础]
      - #chapter("item/map.typ")[映射]
      - #chapter("item/order.typ")[序]
      - #chapter("item/combinatorics.typ")[组合]
    = 微积分
      - #chapter("item/real-numbers.typ")[实数]
      - #chapter("item/limit-sequence.typ")[数列极限]
      - #chapter("item/division-algebra.typ")[可除代数]
      - #chapter("item/Euclidean-space.typ")[Euclidean 空间]
      - #chapter("item/Minkowski-space.typ")[Minkowski 空间]
      - #chapter("item/polynomial.typ")[多项式]
      - #chapter("item/analytic-Euclidean.typ")[解析 (Euclidean)]
      - #chapter("item/analytic-Minkowski.typ")[解析 (Minkowski)]
      - #chapter("item/analytic-struct-operation.typ")[解析 struct 的操作]
      - #chapter("item/ordinary-differential-equation.typ")[常微分方程]
      - #chapter("item/volume.typ")[体积]
      - #chapter("item/integral.typ")[积分]
      - #chapter("item/divergence.typ")[散度]
      - #chapter("item/limit-net.typ")[网极限]
      - #chapter("item/topology.typ")[拓扑]
      - #chapter("item/compact.typ")[紧致]
      - #chapter("item/connected.typ")[连通]
      - #chapter("item/topology-struct-operation.typ")[拓扑 struct 的操作]
      - #chapter("item/exponential.typ")[指数函数]
      - #chapter("item/angle.typ")[角度]
    = 几何
      - #chapter("item/manifold.typ")[流形]
      - #chapter("item/metric.typ")[度规]
      - #chapter("item/metric-connection.typ")[度规的联络]
      - #chapter("item/geodesic-derivative.typ")[Levi-Civita 导数]
      - #chapter("item/curvature-of-metric.typ")[度规的曲率]
      - #chapter("item/Einstein-metric.typ")[Einstein 度规]
      - #chapter("item/constant-sectional-curvature.typ")[常截面曲率]
      - #chapter("item/simple-symmetric-space.typ")[simple-symmetric-space]
      - #chapter("item/principal-bundle.typ")[主丛]
      - #chapter("item/group.typ")[群]
      - #chapter("item/stereographic-projection.typ")[球极投影]
      - #chapter("item/Hopf-bundle.typ")[Hopf 丛]
    = 场论
      - #chapter("item/point-particle-non-relativity.typ")[非相对论点粒子]
      - #chapter("item/point-particle-relativity.typ")[相对论点粒子]
      - #chapter("item/scalar-field.typ")[纯量场]
      - #chapter("item/scalar-field-current.typ")[纯量场的守恒流]
      - #chapter("item/scalar-field-non-relativity.typ")[非相对论纯量场]
      - #chapter("item/projective-lightcone.typ")[光锥射影]
      - #chapter("item/spacetime-momentum-spinor-representation.typ")[时空动量的自旋表示]
      - #chapter("item/Lorentz-group.typ")[Lorentz 群]
      - #chapter("item/spinor-field.typ")[旋量场]
      - #chapter("item/spinor-field-current.typ")[旋量场的守恒流]
      - #chapter("item/electromagnetic-field.typ")[电磁场]
      - #chapter("item/Laplacian-of-tensor-field.typ")[张量场的 Laplacian]
      - #chapter("item/Einstein-metric.typ")[Einstein 度规]
      - #chapter("item/interaction.typ")[相互作用]
      - #chapter("item/harmonic-oscillator-quantization.typ")[谐振子量子化]
      - #chapter("item/spinor-field-misc.typ")[旋量场杂项]
    - #chapter("reference.typ")[参考]
  ]
)

// re-export page template
#import "/templates/page.typ": project
#let book-page = project
