#import "../module/module.typ": *
#show: module

separable ODE in 1 dimension 
$ 
  (#d x)/(#d t) = f(t) g(x) 
  &-->& 1/g(x) #d x = f(t) #d t \
  &-->& x = G^(-1)(F(t)) 
$ 
where $G = integral 1/g(x) #d x, F = integral f(t) #d t$, initial value undetermined

*Example*
- $f(t) = a, g(x) = x$. $x(t) = x(0) exp(a t)$
- $f(t) = 1, g(x) = x^2$. $x(t) = 1/(1/x(0) - t)$

#tag("exponential-of-vector-field") *Question*
#indent[
  let $U$ open in $ℝ^n$

  vector-field is analytic function $v : U -> ℝ^n$

  The exponential-of-vector-field $(exp v) (x)$ generated by the vector field $v$ should be invariant
  
  $ ∂_(v(x)) (exp v) (x) = v(f(x)) $

  Taylor series of vector field 
  $ 
    (exp v) (x) 
    &=& x + v(x) + 1/2! ∂_(v(x)) v(x) + 1/3! ∂_(v(x)) (∂_(v(x)) v(x)) + ⋯ \
    &=& x + sum_(n=0)^∞ 1/((n+1)!) (∂_(v(x)))^n v (x) 
  $
  $n+1$ polynomial like $(∂_(λ v(x)))^n λ v (x) = λ^(n+1) (∂_(v(x)))^n v (x)$
]
*Example* 

compare to the result from separable ODE in 1 dimension

- $v(x) = A(x), A in gl(d,𝕂)$
#indent[  
  compare $vel(x) = A x$, expect $(sum_(0..∞) 1/n! (A t)^n)(x)$ with $t = 1$

  $#d v (x) = A$, $n >= 2 ==> #d^k v (x) = 0$

  $∂_(v(x)) v(x) 
  &=& A(v(x)) \
  &=& A^2 (x)$

  $(∂_(v(x)))^2 v(x) 
  &=& #d (A^2(x))(v(x)) \
  &=& A^2(v(x)) \
  &=& A^3(x) $ 
  
  ...

  $(∂_(v(x)))^n v(x) = A^(n+1) (x)$

  $f(x) = (𝟙 + A + 1/2! A^2 + ⋯) (x) = (sum 1/n! A^n ) (x) = (exp A) (x)$

  $#d f(x) v(x) 
  &=& (exp A)(A (x)) \
  &=& A(exp(A)(x)) \
  &=& v(f(x))$

  *Example* #tag("harmonic-oscillator") 
  #indent[
    make harmonic-oscillator  $acc(x) = ∓ ω^2 x$ first order 
    $
      mat((#d)/(#d t) ; , (#d)/(#d t)) vec(x,v) = mat(, 1 ; ∓ ω^2) vec(x,v)
    $ 
    with the case of trigonometric
    $
      exp t mat(, 1 ; - ω^2) = mat(
        cos ω t , 1/ω sin ω t ;
        - ω sin ω t , cos ω t
      )
    $ 
    so
    $
      x(t) = x_0 cos ω t + v_0/ω sin ω t
    $ 
    or written in the form of complex number and exponential 
    $
      x(t) = 1/2 (x_0 - #i v_0/ω) e^(#i ω t) + 1/2 (x_0 + #i v_0/ω) e^(- #i ω t) =: a (ω, #i) e^(#i ω t) + a (ω, -#i) e^(- #i ω t)
    $
    similar for the case of hyperbolic

    The characteristic polynomial equation of harmonic-oscillator is $ξ^2 ± ω^2 = 0$ or $ξ^2 = ± ω^2$. We are interested in the trigonometric case $ξ^2 + ω^2 = 0$ or $ξ = ω #i ω$, its prototype is $ξ^2 = ± 1$ or $ξ^2 = ± i$

    In the case where the harmonic oscillator $x$ is a real value, for the complex exponential form, in order to remain in $ℝ$, when $x_0,v_0 in ℝ$, the coefficients in front of $e^(± #i ω t)$ are complex conjugates of each other $x_0 ± (v_0)/(#i ω)$
  ]
]
- $ℝ -> ℝ$, $v(x) = x^2$
#indent[
  compare $vel(x) = x^2$, expect $1/(1/x - t)$ with $t = 1$ 

  $∂_(v(x))v(x) = v'(x) v(x) = 2 ⋅ x^3$

  $∂_(v(x))(∂_(v(x))v(x)) = (2 x^3)' v(x) = (2 ⋅ 3) ⋅ x^4$

  ...

  $(∂_(v(x)))^n v (x) = (n+1)! ⋅ x^(n+2)$

  $f(x) 
  &=& x + sum_(n=0)^∞ 1/((n+1)!) (∂_(v(x)))^n v (x) \
  &=& sum_(m=1)^∞ x^m \
  &=& 1 - 1/(1-x)$

  $#d f(x) v(x) 
  &=& (1/(1-x))^2 x^2 \
  &=& (x/(1-x))^2 \
  &=& v(f(x))$
]
*Question* 
#indent[
  The $f(t,x)$ in $f(0,x) = x, f(1,x) = f(x)$ should correspond to the case of a dilation vector field $t ⋅ v(x)$

  One-parameter homomorphism embedding $f(t,x) : ℝ ↪ "Diff"$

  $-v$ and initial value $y = f(x)$ gives $f^(-1)$. $f^(-1)(t,y) = f(-t,y)$
]
$f(t,x)$ is called flow. exp road emission-like coordinates

#tag("vector-field-as-δ-diffeomorphism") Near $𝟙$, the vector field is the coordinate of the diffeomorphism group $v ⇝ exp v$, similar to #raw("#link(<geodesic-coordinate>)[]")

ODE

$ (#d)/(#d t) (exp t v) (x) = v((exp t v) (x)) $

#link("https://en.wikipedia.org/wiki/Cauchy-Kovalevskaya_theorem")[wiki:Cauchy-Kovalevskaya_theorem], the estimation of the radius of convergence uses a special upper bound control method, similar to what is done in #raw("#link(<inverse-analytic>)[]")

$F(x,γ) = (c x)/(x-γ)$, $(#d)/(#d t) γ = F(x,γ)$ ==> $γ(t,x) = x - (x^2 - 2 c t x)^(1/2)$

#tag("integral-curve") Picard iteration of ODE solution (#link("https://en.wikipedia.org/wiki/Picard–Lindelöf_theorem")[wiki]) representation or integral curve e.g.
$
  x(t) = sum_(n = 0 .. ∞) integral_(0)^(t) #d t_(n) integral_(0)^(t_n) #d t_(n-1) ⋯ integral_(0)^(t_0) #d t_1 f(t_n, ⋯ f(t_1, x(0)) ⋯ )
$
If it is a linear ODE, then (*alias* Dyson series)
$
  x(t) = sum_(n = 0 .. ∞) integral_(0)^(t) #d t_(n) integral_(0)^(t_n) #d t_(n-1) ⋯ integral_(0)^(t_0) #d t_1 A(t_n) ⋯ A(t_1) x(0)
$
Linear ODE. The solution of a constant coefficient ODE can be written by transforming it into a first-order differential equation system + Jordan normal form

#tag("Lie-bracket") Lie bracket
#indent[
  as generator of conjugate-action of $"Diff"$

  conjugation action of the $"Diff"$ group $g,f ⇝ f g f^(-1)$

  Differential := $"ad"(v)(w) = [v,w]$

  note that $g,f ⇝ g f g^(-1)$ is a different map, if we consider the order of $g,f$ 

  $[v,w](x) = ∂_(v(x)) w(x) - ∂_(w(x)) v(x)$

  $[v,w] = [w,v]$

  for $GL,gl$, $[A,B] ∼ A B - B A$
]
#let L = c-diff($L$)
#tag("Lie-derivative") Lie derivative *alias* drag derivative
#indent[
  let $v$ generate a one-parameter diffeomorphism $t ⇝ f_t in "Diff"$
  
  let $w_t = #d f_(t)^(-1) (f_t (x) : "base", w(f_t (x)) : "vector")$

  $#L _v (w) := lim_(t -> 0) 1/t (w_t - w_0) $

  $#L _v (w) = [v,w]$
  
  Jacobi identity $#L _([v,w]) = [#L _v,#L _w]$ or $[v_1,[v_2,w_3]] + [v_3,[v_1,v_2]] + [v_2,[v_3,v_1]] = 0$

  Lie derivative can also be defined for tensor fields ...
]
#tag("linear-PDE-integrable-condition") related to the symmetry of the second-order derivative. This condition allows the solution of a first-order linear PDE to come from successive integration curve of ODEs, and the result does not depend on the choice of path