#import "../module/module.typ": *
#show: module

#let H = text("H", fill: rgb("#d25b00"))
#let a = text("a", fill: rgb("#d25b00"))
#let x = text("x", fill: rgb("#006dea"))
#let p = text("p", fill: rgb("#d25b00"))

Approximation of Relativistic Scalar Field Action to Non-Relativistic Scalar Field Action

Using a massive field, extracting the rest energy phase $exp(- m c^2 1/ℏ t #i)$, using time $x_0 = c t$ and the speed of light limit $lim_(c -> ∞)$ 

for #link(<Klein--Gordon-Lagrangian>)[], restore Planck constant $ℏ$, speed of light $c$, time $x_0 = c t$
$
  integral_(ℝ) #d c t integral_(ℝ^3) #d x 1/2 ( 
    1/c^2 (∂_t ϕ^* ∂_t ϕ) 
    - ∂_x ϕ^* ⋅ ∂_x ϕ    
    + (m^2 c^2)/(ℏ^2) ϕ^* ϕ
  )
$
use $ϕ = exp(- m c^2 1/ℏ t #i) ψ$

let $θ = m c^2 1/ℏ #i$

use $∂_t ϕ = θ e^(θ t) ψ + e^(θ t) ∂_t ψ$
$
  ∂_t ϕ^* ∂_t ϕ &= - (m^2 c^4)/(ℏ^2) ψ^* ψ & "use" #i^2 = -1  \
  &quad + (m c^2)/(ℏ) #i (ψ^* ∂_t ψ - ψ ∂_t ψ^*) \
  &quad + ∂_t ψ^* ∂_t ψ
$
the term $- (m^2 c^4)/(ℏ^2) ψ^* ψ$ multiplied by $1/c^2$ will cancel out the mass term $(m^2 c^2)/(ℏ^2) ϕ^* ϕ$

the term $(m c^2)/(ℏ) #i (ψ^* ∂_t ψ - ψ ∂_t ψ^*)$ multiplied by $1/c^2$ will cancel out the speed of light $c$ factor

the term $∂_t ψ^* ∂_t ψ$ multiplied by $1/c^2$ will become $O(1/c^2 (∂_t ψ^* ∂_t ψ))$, vanishing in the limit $lim_(c -> ∞)$

$#d x^0 = #d c t$ might not affect it?

Multiply the entire expression by $ℏ^2/m$ to get

Non-relativistic scalar field Lagrangian, *alias* Schrodinger-Lagrangian #tag("Schrodinger-Lagrangian")
$
  integral_(ℝ) #d t integral_(ℝ^3) #d x 1/2 (
    ℏ #i (ψ^* ∂_t ψ - ψ ∂_t ψ^*)     
    - ℏ^2/m ∂_x ψ^* ⋅ ∂_x ψ
  ) 
$
Can add a gauge field electrostatic potential term to the action, i.e., change $∂_t$ to $∂_t + #i/ℏ V$

Non-relativistic scalar field equation, *alias* Schrodinger-equation #tag("Schrodinger-equation")
$
  #i ℏ ∂_t ψ = - ℏ^2/(2 m) ∆ ψ + V ψ 
$
For either relativistic or non-relativistic scalar fields, it's possible to use a time plane wave mixed static solution $exp(- 1/ℏ E t #i) ψ(x)$ to obtain the eigenvalue equation
$
  - ℏ^2/(2 m) ∆ ψ + V ψ = E ψ 
$
One can also add static magnetic potential, $∂_x$ is changed to $(∂_x + #i/ℏ A) ψ$, with 

$(∂_x + #i/ℏ A)^† (∂_x + #i/ℏ A) ψ = (∆ + #i/ℏ div A + (2 #i)/ℏ A ⋅ ∂_x - 1/ℏ^2 |A|^2) ψ$

#tag("Schrodinger-eq-potential-example") *Example* 
- $V = k r^2$ 

  Resonator (one or more) represents the electric potential of constant charge density in $ℝ^n$ or spherical regions. $div grad r^2 = "const"$. Opposite charges correspond to elliptical type, same charges correspond to hyperbolic type.

- $V = k 1/r$

  $ℝ^3$ Hydrogen atom model (single particle, static, electrostatic, zero spin) represents a spherically symmetric electric potential generated by a point charge or a spherically symmetric charge sphere.
  
  Using symmetry + Gauss's theorem
  
  Or using differential equations, spherical symmetry $f(x) = f(|x|) = f(r)$ + charge concentrated at a point or spherical region, then outside $∆ f(r) = 0$ ==> $2 1/r (#d f)/(#d r) + (#d^2 f)/(#d r^2) = 0$ ==> $f(r) = k 1/r$

  #link("https://en.wikipedia.org/wiki/Hydrogen-like_atom")[wiki:Hydrogen-like_atom]

  *_Warning_* The Schrodinger equation has no analytical solution for atoms and molecules other than hydrogen atoms for the time being. I also don't know the existing multi-particle models and how effective their numerical calculations are.

- $V = $ box/ball potential well/barrier

- constant electric field or constant magnetic field

Regarding the non-relativistic approximation limit

- Static energy phase extraction $exp(- m c^2 1/ℏ t #i)$ is not a gauge transformation.
- Can $ℂ$ be generalized to $ℍ,𝕆$? Replace $#i$ with any $Im(𝕂)$ unit element. $ℝ$ doesn't work? Or $ℝ$ is used for hyperbolic mass KG rather than elliptical mass KG, in one-dimensional $ℝ$ the equation $x^2 = -1$ cannot be solved)
- This method of non-relativistic approximation limit is coordinate-dependent. On curved manifolds, since multiple coordinates may be needed to cover the entire manifold, the definition problem of the non-relativistic approximation limit will be more difficult.

Symmetry and Conserved Current

let 
$
  L(ψ,∂_t ψ,∂_x ψ) = 1/2 (
    ℏ #i (ψ^* ∂_t ψ - ψ ∂_t ψ^*) 
    - ℏ^2/m ∂_x ψ^* ⋅ ∂_x ψ
  )
$
Similar to the case of relativistic scalar field, energy-momentum tensor #tag("energy-momentum-tensor-Schrodinger")
$
  T = T^(μ)_(ν) = cases(
    (∂ L)/(∂ (∂_(ν) ψ)) ⋅ ∂_(ν) ψ - L & " if " μ = ν ,
    (∂ L)/(∂ (∂_(μ) ψ)) ⋅ ∂_(ν) ψ & " if " μ != ν
  )
$
Time
$
  (∂ L)/(∂ (∂_t ϕ)) ⋅ ∂_(ν) ψ 
  &= 1/2 ℏ #i (ψ^* ∂_(ν) ψ - ψ ∂_(ν) ψ^*) \
  &= ℏ #i Im(ψ^* ∂_(ν) ψ) \
$
Space
$
  (∂ L)/(∂ (∂_x ϕ)) ⋅ ∂_(ν) ψ 
  &= - (ℏ^2)/(2m) (∂_(ν) ψ^*  ∂_x ψ + ∂_x ψ^* ∂_(ν) ψ) \
  &= - (ℏ^2)/(2m) Re(∂_x ψ^* ∂_(ν) ψ)
$
Energy
$
  E = integral_(ℝ^3) #d x (T^0_0) 
  = integral_(ℝ^3) #d x ((ℏ^2)/(2m) |∂_x ψ|^2)
$
Using the product rule $∂_x^† (ψ^* ∂_x ψ) = ∂_x ψ^* ∂_x ψ + ψ^* ∂^†_x ∂_x ψ$ + divergence term + zero at boundary, it becomes 
$
  integral_(ℝ^3) #d x (- (ℏ^2)/(2m) ψ^* ∆ ψ) = ⟨ #H ⟩_(ψ)
$
If there is an electrostatic potential $V(x)$, it will still be $⟨ #H ⟩_(ψ)$, but it might become non-positive definite

Due to the zero divergence of the energy-momentum tensor, energy is conserved with respect to time $t$, $∂_t E = 0$

For non-relativistic scalar fields, the energy of the Schrodinger field is real, positive and time invariant

Rotational angular momentum is #tag("angular-momentum-Schrodinger")
$
  M^k_(i j) = [x_i,T^k_j]
$
Gauge current of the Schrodinger field

Phase change $e^(θ(x)) ϕ(x)$ and its δ change $θ ϕ$ belong to variations with fixed boundaries near the solution, so

The spatial part of the current is similar to the relativistic case, $(ℏ^2)/(2m) (ψ^* ∂_x ψ - ψ ∂_x ψ^*) = (ℏ^2)/(m) Im(ψ^* ∂_x ψ)$

The time part of the current ($θ(x) ∈ Im(ℂ)$)
$
  ℏ Im ( (- θ ψ^*) ∂_t ψ + ψ^* ∂_t (θ ψ) )= ℏ Im (ψ^* ψ ∂_t θ)
$ 
The result will be the quantity $#i ℏ ψ^* ψ$

The entire current, after dividing by $#i ℏ$, is $(ψ^* ψ, - (#i ℏ)/(2m) (ψ^* ∂_x ψ - ψ ∂_x ψ^*)$ #tag("current-gauge-Schrodinger")

The time component of the Schrodinger field gauge current is real, and the spatial component is purely imaginary

Assume $j$ is an integrable quantity in $ℝ^3$

time-invariant $∂_0 integral_(ℝ^3) #d x ( j^0 ) = 0$ by $∂^† T = 0$ #tag("conserved-spatial-integral-charge-Schrodinger")
$ 
  integral_(ℝ^3) #d x ( j^0 ) 
  &= integral_(ℝ^3) #d x (ψ^* ψ) \
  &= integral_(ℝ^3) #d x |ψ|^2 
$
The time component of the Schrodinger field current is positive and its spatial integral is time invariant

Should this quantity be "particle number density" or "probability density" or "charge density"?

#tag("motivation-of-quantization")
#indent[
  Most treatments of quantization assume

  - Linear unitary evolution of $ℂ$ field

  - Possibly non-free fields, so plane waves cannot be used

  If the non-relativistic approximation limit of the KG field is considered, these assumptions will be automatically obtained.

  Then, the time component of the static gauge field acts as the electric potential. Both the harmonic oscillator potential $k r^2$ (uniform Charge) (probably should not be interpreted this way) and the hydrogen atom potential $k 1/r$ (point charge) originate from simple charge densities.

  Thus, the motivation problem becomes:

  - Why use $ℂ$ KG field?

  - Why and how does it correspond to point particles?

  - Why does the potential of a gauge field become the potential of a particle when the field is quantized into particles?

  Classical correspondence refers to the expectation value version of the point particle Lagrange-equation (@ref-15, p.116) (#link("https://en.wikipedia.org/wiki/Ehrenfest_theorem")[wiki:Ehrenfest_theorem]), e.g. $m (#d^2)/(#d t^2) ⟨ #x ⟩_(ψ_t) = ⟨ - (#d V)/(#d x) ⟩_(ψ_t)$ 

  there also new operator in the speed of expectation $m (#d)/(#d t) ⟨ #x ⟩_(ψ_t) = 1/(#i ℏ) ⟨ [#x,#H] ⟩_(ψ_t) = ⟨ - #i ℏ (∂)/(∂ x) ⟩_(ψ_t) =: ⟨ #p ⟩_(ψ_t)$
  
  Where the non-commutativity $[#x,#H] = #i ℏ #p$ or $⟨ [#x,#H] ⟩_(ψ) = #i ℏ ⟨ #p ⟩_(ψ)$ is controlled by the very small Planck constant $ℏ$

  Note the difference between classical energy and quantum energy, similar to the difference between mean and variance. For example, $⟨ #p ⟩^2 != ⟨ #p^2 ⟩$. We can consider the standard deviation $Δ #p = (⟨ #p^2 ⟩ - ⟨ #p ⟩^2)^(1/2)$. There is the uncertainty principle $1/2 ℏ = 1/2 |#i [#x,#p]| <= Δ #x ⋅ Δ #p$. The equality holds <==> #link(<harmonic-oscillator-ground-state>)[]

  The Schrodinger eq is the non-relativistic limit of the $ℂ$ KG eq, and Newton's equation is the non-relativistic limit of relativistic point particles. So, can it be proven that the KG eq also has a point particle limit? At this point, should the definition of "expectation" use the charge density of the $#U (1)$ KG, $- ϕ^* ∂_t ϕ + ϕ ∂_t ϕ^*$. However, the charge of the KG eq is not positive definite, making it even further from the meaning of classical particles. However, the energy of the KG eq is positive definite (even with electromagnetic potential). For the Dirac eq, the charge is positive definite but the energy is not positive definite.

  How to make the expected value version of the point particle Lagrange-equation correspond to the Lagrange-equation of the field?

  Other signs that the Schrodinger wave function corresponds to point particles:

  - Feynman path integrals use the path statistics weighted by the point particle Lagrangian to calculate the propagator of the Schrodinger eq. *Question* proof that it satisfies Ehrenfest theorem and then satisfies Schrodinger eq
]
#tag("quamtum-operator-motivation") 
#indent[
  The derivation of the behavior of the Schrodinger wave function under Galileo transformation, in brief, assumes that in addition to the non-relativistic space-time coordinate transformation $(t',x') = (t + Δ t, R x + v t + Δ x)$, it is also assumed that the wave function changes phase $ψ(t,x) ⇝ e^(#i/ℏ f(t',x')) ψ(t',x')$, the result will be (@ref-16)
  
  $
    f(t',x') &= - m v ⋅ x' + 1/2 m v^2 t' \
    &= - m v (R x + v t + Δ x) + 1/2 m v^2 (t + Δ t)
  $

  *Question* Simplified calculations and better motivated explanations for the phase transformation? Perhaps it can be related to the use of static energy phase when KG eq is approximated to Schrodinger eq. In short, neither Schrodinger eq nor electromagnetic field are purely Galileo transformation invariant.
  
  Galileo boost $x + v t, v in ℝ^3_"boost"$ gives the transformation of the wave function $ψ$ as $e^(- #i/ℏ (m v x + 1/2 m v^2 t)) ψ(t,x + v t)$, the δ action of this action is the operator $#i/ℏ (t #p - m #x)$

  Time translation $t + a, a in ℝ_"time"$ -> δ action $∂_t = - #i/ℏ #H$, Hamiltonian

  Spatial translation $x + a, a in ℝ^3_"space"$ -> δ action $∂_x = #i/ℏ #p $, momentum operator

  Rotation $R x, R in SO(3)$ -> δ action $#i/h (#x × #p)$, angular momentum operator

  Phase $e^(#i ℏ θ) ψ, e^(#i ℏ θ) in #U (1)$ -> δ action $#i ℏ 𝟙$

  For QM in $ℝ^1$ space, the Lie bracket of boost and spatial translation $[#i/ℏ (t #p - m #x), #i/ℏ #p] = m/ℏ^2 [#x,#p] = m #i/ℏ 𝟙$, or equivalently $[#x,#p] = #i ℏ 𝟙$
]
#tag("motivation-of-eigenstate") 
#indent[
  Mimicking the finite-dimensional case, diagonalize one quadratic form with an orthonormal basis in a (positive definite) quadratic form space.

  Using differentiation to find the extreme values or first-order stable values of the Hermitian operator $#H$

  on ${|ψ|^2 = 1}$, let $Δ ψ in ψ^⟂$ (orthogonal in the sense of $Re ⟨ Δ ψ , ψ ⟩ = 0$)

  Another quadratic form $x^⊺ H x$ on a finite-dimensional standard quadratic form corresponds to an infinite-dimensional case where the wave function is in some $L^2$ or Hilbert space, acting as a quadratic form space. The energy $⟨ ψ mid(|) #H mid(|) ψ ⟩$ is another quadratic form.

  Its first derivative $Re ⟨ Δ ψ mid(|) #H mid(|) ψ ⟩ = 0$ forall $Δ ψ in ψ^⟂$ ==> $#H ψ in ψ^(⟂ ⟂) = span{ψ}$ ==> exists $E in ℝ, #H ψ = E ψ$

  States with different eigenvalues are orthogonal
  $
    ⟨ ψ' mid(|) #H mid(|) ψ ⟩ = E ⟨ ψ' , ψ ⟩ = E^' ⟨ ψ' , ψ ⟩ 
    &==> (E - E') ⟨ ψ' , ψ ⟩ = 0 \
    &==> ⟨ ψ' , ψ ⟩ = 0
  $
  There exists an orthogonal basis $e_1 ,…, e_n$ for a finite-dimensional standard quadratic form, such that $x = x_1 e_1 + ⋯ + x_n e_n$, and $H$ is in a form close to a standard quadratic form, i.e., diagonalizing $x^⊺ H x = λ_1 x_1^2 + ⋯ + λ_n x_n^2$. $H$ can be written as $mat(λ_1 ; , ⋱ ; ,, λ_n)$ or $sum_(k = 1 .. n) λ_k ket(e_k) bra(e_k)$. The corresponding infinite-dimensional case is that there exists an orthogonal basis of the Hilbert space such that the energy $⟨ ψ mid(|) #H mid(|) ψ ⟩$ is diagonalized. However, in the case of Hilbert space, diagonalization of the energy expectation might be in the form of a countable sum.
  $
    ψ &= sum_(k in ℕ) a_k ψ_k \
    ⟨ ψ mid(|) #H mid(|) ψ ⟩ &= sum_(k in ℕ) λ_k |a_k|^2 \
    #H &= sum_(k in ℕ) λ_k ket(ψ_k) bra(ψ_k)
  $
  However, sometimes a countable sum is not enough, and an integral form is required, and the orthogonal basis is not the $L^2$ space where the wave function resides, even if the coefficients of the wave function's orthogonal basis expansion might be in the $L^2$ space of the eigenvalues. (*Question* What is the specific construction method for the $L^2$ structure of the eigenvalue space?) An example is the existence of unbound states in the electrostatic hydrogen atom model.

  Schrodinger eq evolution preserves the eigenvalue space

  The energy is a quadratic form, and its second-order differential polynomial is $⟨ Δ ψ mid(|) #H mid(|) Δ ψ ⟩$
  
  Divide the space into the $E$ eigenspace $V_E$ and its orthogonal complement $V_E^(⟂)$. In the $V_E^⟂$ direction, the second-order differential is positive definite or negative definite, and the energy will increase or decrease. According to Lagrangian variational theory, the energy of the Schrodinger eq is a time-conserved quantity $⟨ #H ⟩_(ψ_t) ≡ ⟨ #H ⟩_(ψ_0) = E$
  
  $V_E, V_E^⟂$ are separated in the sense of limit, unless at $0$. $⟨ ψ , ψ ⟩ = 1 ==> ψ != 0$, so the evolution will be confined to the $E$ eigenspace $ψ_t in V_E$

  Specific solution for the Schrodinger eq evolution in the eigenvalue space. $#i ℏ ∂_t ψ (t,x) = #H ψ (t,x) = E ψ (t,x)$ is a constant-coefficient linear ODE from $ℝ -> ℂ$ for each spatial point $x$, solution $ψ (t,x) = e^(- #i/ℏ E t) ψ (0,x)$ i.e., essentially static $ψ (0,x)$ except for the phase factor $e^(- #i/ℏ E t)$ which oscillates in time according to $#U (1)$.
]