#import "/module/module.typ": *
#show: module

#let p = spin($p$)
#let q = spin($q$)

#tag("co-vector-of-Hermitian-tensor") 
#indent[
  $ϕ$ derives the co-vector of #link(<Hermitian-tensor>)[]
  $
    dmat( delim: #none ,
      ⨀^(* 2) ℂ^2 , ⟶ , ℝ ;
      #p , ⟿ , ϕ^† #p^⬨ ϕ
    )
  $
  where $#p^⬨$ is #link(<parity>)[]. Since $#p ∈ ⨀^(* 2) ℂ^2$ is a Hermitian matrix, then $(#p^⬨)^† = #p^⬨$, so $(ϕ^† #p^⬨ ϕ)^† = ϕ^† #p^⬨ ϕ$, so $ϕ^† #p^⬨ ϕ in ℝ$
  
  It can be considered that $#p$ acts symmetrically on the two slots $ϕ^† (#p^⬨ ϕ) = (ϕ^† (#p^⬨ ϕ))^† = (#p^⬨ ϕ)^† ϕ$

  The base of the co-vector space $σ^0,σ^1,σ^2,σ^3 ∈ Lin(ℝ^(1,3) -> ℝ)$ gives the coefficients of the co-vector $ϕ^† (σ^μ)^⬨ ϕ in ℝ$

  $(1/2,0)$ action is derived to the action on the co-vector $ϕ$
  $
    (A ϕ)^† #p^⬨ (A ϕ) 
    &= ϕ^† (A^† #p^⬨ A) ϕ \
    &= ϕ^† (A^(-1) #p^⬨ (A^†)^(-1))^⬨ ϕ & "use" #link(<property-of-paristy>)[] \
    &= ϕ^† ((A^(⊙ * 2))^(-1) #p)^⬨ ϕ 
  $

  The parity dual of $ϕ^† #p^⬨ ϕ$, $ϕ$ derives the co-vector

  $ #p ⟿ ϕ^† #p ϕ $

  $(0,1/2)$ action $A^†$ is derived to the action on the co-vector

  Similarly, co-vectors can also be defined for anti-Hermitian
  $
    dmat( delim: #none ,
      ⋀^(* 2) ℂ^2 , ⟶ , Im(ℂ) ;
      P , ⟿ , ϕ^† P^⬨ ϕ
    )
  $
  For conjugate 2 order tensors
  $
    dmat( delim: #none ,
      ⨂^(* 2) ℂ^2 , ⟶ , ℂ ;
      P , ⟿ , ϕ^† P^⬨ ϕ
    )
  $
]
#tag("spinor-field-motivation?") 
#indent[
  - formally corresponds momentum $p$ to gradient momentum $#i ⋅ (∂_0,∂_1,∂_2,∂_3)$, and $#p$ to #link(<spacetime-momentum-spinor-representation>)[] $#i ⋅ mat(
      ∂_0 + ∂_1, ∂_2 + ∂_3 #i ;
      ∂_2 - ∂_3 #i, ∂_0 - ∂_1
    )$

  - formally used for co-vector generated by $ϕ$ to obtain $ℂ$ field
    $
      &ϕ^† #i ⋅ mat(
      ∂_0 + ∂_1, ∂_2 + ∂_3 #i ;
      ∂_2 - ∂_3 #i, ∂_0 - ∂_1
      )^⬨ ϕ 
    $
  - action + product rule + divergence quantity + boundary zero + integral quadratic form ==> self-adjoint operator $#i ⋅ mat(
      ∂_0 + ∂_1, ∂_2 + ∂_3 #i ;
      ∂_2 - ∂_3 #i, ∂_0 - ∂_1
    )$ 
    $
      ⟨ ϕ, #i #spin-d^⬨ ψ ⟩_(L^2) = ⟨ #i #spin-d^⬨ ϕ, ψ ⟩_(L^2)
    $
  ]


#show "Δ": it => text(it, fill: rgb("#0056e1"))
#tag("massless-spinor-Lagrangian") (cf. #link(<Lagrangian>)[]), *alias* #tag("Weyl-Lagrangian")
#indent[
  $ ϕ^† #i #spin-d ^⬨ ϕ $

  or $ϕ^† (σ^⬨ ⋅ #i ∂) ϕ$ or $ϕ^† (σ^(μ ⬨) #i ∂_μ) ϕ$

  where $L^2$ is integrated with $ℝ^(1,3)$ + quadratic form $ϕ^† ψ$ of $ℂ^2$

  Only $Re ϕ^† (σ^(μ ⬨) #i ∂_μ) ϕ = - #i Im ϕ^† (σ^(μ ⬨) #i ∂_μ)$ is effective, because $Im ϕ^† (σ^(μ ⬨) #i ∂_μ) ϕ = #i Re ϕ^† (σ^(μ ⬨) ∂_μ) ϕ = #i ∂_μ (ϕ^† σ^(μ ⬨) ϕ) = #i div(ϕ^† σ ϕ)$ is a divergence quantity, using Stokes' theorem + zero boundary

  Variation gives linear part $integral 2 Re (Δ ϕ)^† #i #spin-d^⬨ ϕ$ 
]
#tag("massless-spinor-equation"), *alias* #tag("Weyl-equation")
#indent[
  $ #spin-d^⬨ ϕ = 0 $

  or $(σ^⬨ ⋅ ∂) ϕ = 0$ or $(σ^(μ ⬨) ∂_μ) ϕ = 0$

  Similar to $ℂ^2 ≃ ℝ^2$ via $x ± y #i$, variation for $ℂ$-valued $ϕ$ is equivalent to variation for $ℝ$-valued $ϕ,ϕ^†$

  $#spin-d ϕ = (σ ⋅ ∂) ϕ = (σ^μ ∂_μ) ϕ$ can be interpreted as (after metric-adjoint) gradient $∂ ϕ ∈ ℝ^(1,3) ⊗ ℂ^2$ spacetime-momentum-spinor + multiplication of spinors $(#p ⊗ ψ ⇝ #p ψ) ∈ ℝ^(1,3) ⊗ ℂ^2 -> ℂ^2$
]
#tag("Weyl-parity")
#indent[
  Parity dual action uses $(0,1/2)$ spinor

  $ ϕ^† #i #spin-d ϕ $

  Parity dual eq

  $ #spin-d ϕ = 0 $

  or $(σ ⋅ ∂) ϕ = 0$ or $(σ^μ ∂_μ) ϕ = 0$
]
#tag("Weyl-eq-plane-wave")
#indent[
  Plane wave solution $Φ e^(- #i p x)$ with $p^2 = m^2$ and $#p Φ = 0$
  
  A linear equation with $det #p = p^2 = 0$ indicates a non-zero solution. The solution space is one-dimensional, and the solution can be written as $Φ = #p^⬨ ξ$ with $dim(im(#p^⬨)) = 1$
  
   
]
#tag("massive-spinor-Lagrangian") mass couples the spinor action, *alias* #tag("Dirac-Lagrangian")
#indent[
  couple $(1/2,0),(0,1/2)$ to $(1/2,0) ⊕ (0,1/2)$

  $mat(A;,(A^†)^(-1)) vec(ϕ,ψ) = mat(A ϕ; (A^†)^(-1) ψ)$

  $#p in ⨀^(* 2) ℂ^2$, $#p ⇝ mat(#p^⬨;,#p)$

  $ Im vec(ϕ,ψ)^† (mat(#i #spin-d^⬨;, #i #spin-d) - m mat(,𝟙;𝟙)) vec(ϕ,ψ) $

  invariant non couple term $vec(ϕ,ψ)^† mat(#i #spin-d^⬨;,#i#spin-d) vec(ϕ,ψ) = #i ϕ^† #spin-d^⬨ ϕ + #i ψ^† #spin-d ψ$

  invariant couple term $- vec(ϕ,ψ)^† m mat(,𝟙;𝟙) vec(ϕ,ψ) = - m (ϕ^† ψ + ψ^† ϕ) = - 2 m Re ϕ^† ψ = 2 m Im ψ^† ϕ$

  Varying the couple term with respect to $ϕ$ gives $integral - 2 m Re (Δ ϕ)^† ψ$

  - The overall variation with respect to $ϕ$ gives $#i #spin-d^⬨ ϕ - m ψ = 0$
  - The overall variation with respect to $ψ$ gives $#i #spin-d ψ - m ϕ = 0$

  When $m = 0$, it decouples into two parity-dual massless-spinors


  They imply 
  $
    #spin-d #spin-d^⬨ ϕ + m^2 ϕ = 0 \
    #spin-d^⬨ #spin-d ψ + m^2 ψ = 0
  $
  and $∆ = #spin-d #spin-d^⬨ = #spin-d^⬨ #spin-d$ as "square root of $∆$" #tag("square-root-of-spacetime-Laplacian") 

  Overall $(∆ + m^2) vec(ϕ,ψ) = 0$, square root of KG

  All partial derivatives $(∂ S)/(∂ ϕ) = (∂ S)/(∂ ψ) = 0$, giving #tag("massive-spinor-equation"), *alias* #tag("Dirac-equation")

  $ (mat(#i #spin-d^⬨;,#i #spin-d) - m mat(,𝟙;𝟙)) vec(ϕ,ψ) = 0 $
]
Similar to $ℂ^2 ≃ ℝ^2$ via $x ± y #i$, varying with respect to $ℂ^2$-valued $ϕ,ψ$ is equivalent to varying with respect to $ℝ^2$-valued $vec(ϕ,ψ),vec(ϕ,ψ)^†$

Replacing the couple term $-m mat(,𝟙;𝟙), m ∈ ℝ$ with $-mat(,n 𝟙;m 𝟙),m,n ∈ ℂ$, the action remains invariant. But the equation can no longer be decomposed into that simpler form

*Question* forall $A ∈ SL(2,ℂ)$ invariant matrix $mat(A ;, (A^†)^(-1))^† mat(M_1,M_2;M_3,M_4) mat(A ;, (A^†)^(-1)) = mat(A^† M_1 A, A^† M_2 (A^†)^(-1); A^(-1) M_3 A, A^(-1) M_4 (A^†)^(-1)) = mat(M_1,M_2;M_3,M_4)$ probably only $mat(,n 𝟙;m 𝟙),m,n ∈ ℂ$

#tag("Dirac-eq-plane-wave") Plane wave solution $vec(Φ, Ψ) e^(- #i p x)$ with $p^2 = m^2$ and $(mat( #p ;,#p^⬨) - m mat(,𝟙;𝟙)) vec(Φ,Ψ) = 0$ 
  
The latter is a linear equation, so the solution is not difficult. The solution space is two-dimensional, and the solution can be written as $vec(Φ,Ψ) = vec(#p^(⬨ 1/2) ξ, #p^(1/2) ξ), ξ ∈ ℂ^2$

#tag("squrae-root-of-spacetime-momentum-spinor-representation") 
#indent[
  Although it might be possible to use the eigenvalues of the Hermite matrix $#p$ ($p_0 ± (p_0^2 - m^2)^(1/2)$), we will calculate it directly here. let $#p = #q^2$ or
  $
    mat(
      p_0 + p_1 , p_2 + #i p_3 ;
      p_2 - #i p_3 , p_0 - p_1
    )
    = mat(
      (q_0 + q_1)^2 + q_2^2 + q_3^2 , 2 q_0 (q_2 + #i q_3) ;
      2 q_0 (q_2 - #i q_3) , (q_0 - q_1)^2 + q_2^2 + q_3^2
    )
  $
  ==>
  $
    p_0 &= q_0^2 + q_1^2 + q_2^2 + q_3^2 \
    p_1 &= 2 q_0 q_1 \
    p_2 + #i p_3 &=  2 q_0 (q_2 + #i q_3) 
  $
  ==> Use $p_1^2 + p_2^2 + p_3^2 = p_0^2 - m^2$
  $
    p_0 = q_0^2 + 1/(4 q_0^2) (p_0^2 - m^2)
  $
  Quadratic equation for $q_0^2$: $(q_0^2)^2 - p_0 (q_0^2) + 1/4 (p_0^2 - m^2)$, solution
  $
    q_0^2 = 1/2 (p_0 ± m)
  $
  ==>
  $
    q_0 &= (1/2 (p_0 ± m))^(1/2) \
    &= frac(p_0 + m,(2 (p_0 ± m))^(1/2)) \

    i = 1,2,3 => q_i &= frac(p_i,(2 (p_0 ± m))^(1/2))
  $
  or 
  $
    #p^(1/2) &= frac(
      #p ± m 𝟙 ,
      (2 (p_0 ± m))^(1/2)
    ) \
    "and " 
    #p^(⬨ 1/2) &= frac(
      #p^⬨ ± m 𝟙 ,
      (2 (p_0 ± m))^(1/2)
    )
  $
  Still Hermite. Calculation yields
  $
    #p^(1/2) #p^(⬨ 1/2) = m = #p^(⬨ 1/2) #p^(1/2)
  $

  *Example* 
  #indent[
    If $p = (p_0,p_1,0,0), p_0 > 0$, then $#p^(1/2) = mat((p_0 + p_1)^(1/2);,(p_0 - p_1)^(1/2))$ and $#p^(⬨ 1/2) = mat((p_0 - p_1)^(1/2);,(p_0 + p_1)^(1/2))$. If $p_1 = 0$ as well, then $vec(#p^(1/2) ξ, #p^(⬨ 1/2) ξ) = p_0^(1/2) vec(ξ,ξ)$
  ]

  $vec(#p^(1/2) ξ, #p^(⬨ 1/2) ξ)^† vec(#p^(1/2) ξ, #p^(⬨ 1/2) ξ) &= ξ^† (#p + #p^⬨) ξ \
  &= (2 p_0) |ξ|^2 \
  &= (tr #p) |ξ|^2$ 
]

1,3 metric square root or $∆$ square root $mat(#p^⬨;,#p) mat(#p ;,#p^⬨) = (det #p) mat(𝟙;,𝟙)$. But you can also use $#p ⇝ mat(,#p^⬨;#p)$ to get the true square $mat(,#p^⬨;#p)^2 = (det #p) 𝟙$. Since $mat(#p ;,#p^⬨)^2 != (det #p) 𝟙$, the transformation between $mat(#p ;,#p^⬨)$ and $mat(,#p ; #p^⬨)$ is not a coordinate change $T^(-1) ⋅ M ⋅ T$ in $GL(4,ℂ)$.

#tag("motivation-of-gauge-field?") 
#indent[
  Some issues were ignored

  The tangent projective light cone bundle is well-defined

  Do we really need $ℂ^2$ fields or $ℂℙ^1$ fields? There are too many choices for lifting $ℂℙ^1$ fields to $ℂ^2$ fields (or lifting to $ℂ^2 ∖ 0$ fields), unlike $SO(1,3)$ lifting to $SL(2,ℂ)$ where there are only two. On curved manifolds, there might not even be a continuous single-valued lift.

  The $ℂ^2$ bundle over curved spacetime can be directly defined in the bundle coordinates of the $SO(1,3)$ principal bundle (orthonormal frame bundle). When changing coordinates, $SL(2,ℂ)$ is automatically derived from $SO(1,3)$.

  In curved spacetime, the covariant derivative of spinor fields needs to be handled and derived from #link(<metric-connection>)[]. 
  
  For derivatives, an orthonormal frame should be used instead of a coordinate frame, i.e., using the $SO(1,3), SL(2,ℂ)$ principal bundle.

  Although we already have a $ℂ^2$ bundle, lifting $ℂℙ^1$ to $ℂ^2$ introduces additional symmetry. We can multiply the spinor $ϕ(x)$ by $a(x) = |a(x)| exp(θ #i) ∈ GL(1,ℂ) = ℝ_(> 0) × #U (1)$ to change the gauge to $a(x) ϕ(x)$, which remains the same in the projective $ℂℙ^1$.

  Changing the gauge is incompatible with taking derivatives in the tangent space in bundle coordinates, so an additional structure --- #link(<principal-bundle-connection>)[connection] --- must be introduced.
  
  There are many possible connections.
  
  There are connections that cannot be made locally flat; in every gauge, the connection field cannot be eliminated.
  
  Similar to gravity, the concept of local flat connection <==> local curvature 0 is needed, and the connection is chosen by minimizing curvature.
  
  Even if the topology of the spacetime base manifold is non-trivial, different bundle types may exist.

  If simple conserved currents for the action are desired, use $#U (1)$ gauge transformations instead of $ℂ ∖ 0 = #U (1) × ℝ_(> 0)$. $#U (1)$ does not change the Lagrangian action, which simplifies calculations when computing conserved currents (cf. the case of scalar fields).

  One problem is that the gauge bundle does not seem to be directly related to the tangent bundle.
  
  It seems necessary to consider all types of $#U (1)$ bundle types based on the underlying manifold simultaneously

  In the homotopy sense, $ℝ^(p,q)$ has only one type of $#U (1)$ bundle type
]
#tag("spin-connection")
#indent[
  The $SO(1,3)$ #link(<principal-bundle>)[frame bundle] derived from the tangent bundle metric and the #link(<principal-bundle-connection>)[connection] derived from #link(<metric-connection>)[] are expressed as $Γ$ is locally type $(ℝ^(1,3))^⊺ ⊗ so(1,3)$, acting on the tangent field $ℝ^(1,3)$ by $∂ + Γ$

  The way to derive the spin-connection is to #link(<square-root-of-Lorentz-Lie-algebra>)[map the $so(1,3)$ part of the induced metric-connection $Γ$ to $sl(2,ℂ)$] in the orthonormal-frame, obtaining the connection of the $SL(2,ℂ)$ bundle, locally type $(ℝ^(1,3))^⊺ ⊗ ℂ^2$, acting on the spinor field $ℂ^2$ by $∂ + ω$ with $ω = ω^(μ ν) 1/4 [σ_(μ),σ_(ν)]_(⬨)$
]
spin-connection also denoted by $∇$

#tag("motivation-of-scalar-field?") can scalar field be related to tautological bundle of projective-lightcone $ℂℙ^1$?

According to the concept of spinor fields on $ℝ^(1,3)$ spacetime manifold, "rotation by 720 degrees" and "parity" should occur in the tangent space construction rather than in the spacetime manifold.

Since the tangent spaces of spacetime manifolds are all $ℝ^(1,3)$, can spinor fields be generalized to general spacetime manifolds?

#tag("spinor-on-Lorentz-manifold") *Question*
#indent[
  massless-spinor-action
  $
    integral #d Vol(g) (ψ^† #i #spin-connection^⬨ ψ)
  $
  massless-spinor-equation
  $
    #spin-connection^⬨ ψ = 0
  $
  Perhaps a conceptually incorrect definition? Compare with flat spacetime, try to prove or disprove
  - $#i #spin-connection^⬨$ is self-adjoint 
  - Only $Re (ψ^† #spin-connection^⬨ ψ)$ plays a role in the variation of the action
  - $#spin-connection^⬨ #spin-connection = #spin-connection #spin-connection^⬨ = 1/2 (∇^† ∇ + ∇ ∇^†)$ i.e. square-root-of-spacetime-Laplacian

  massive-spinor-Lagrangian
  $
    integral #d Vol(g) Re vec(ϕ,ψ)^† (mat(#i #spin-connection^⬨ ;,#i #spin-connection) + m mat(,𝟙;𝟙)) vec(ϕ,ψ)
  $
  massive-spinor-equation
  $
    (mat(#i #spin-connection^⬨ ;,#i #spin-connection) + m mat(,𝟙;𝟙)) vec(ϕ,ψ) = 0
  $
]
*Question* As long as we locally quotient back from $ℂ^2$ to $ℂℙ^1$, we can avoid the problem of continuous global single-valued lift to $ℂ^2$.

We know that the KG eq has a non-relativity approximation limit $lim_(c -> ∞)$. Does the massive-spinor construction have a non-relativity approximation limit $lim_(c -> ∞)$?

Static does not require a non-relativity approximation limit $lim_(c -> ∞)$, despite the presence of $c$, just as static electromagnetic field equations do not require a non-relativity approximation limit $lim_(c -> ∞)$. This is also true for the KG equation.

let $ϕ(t,x) = ϕ(x)$ static

static massless spinor eq
$
  σ^i ∂_i ϕ = 0
$
static massive spinor eq
$
  (mat(- #i σ^i ∂_i ;, #i σ^i ∂_i) + (m c) / (ℏ) mat(,𝟙;𝟙)) vec(ϕ,ψ) = 0
$
They can couple to static electromagnetic gauge potential $(V(x),A_(1,2,3)(x))$ or just static electric $V(x)$ or just static magnetic $A_(1,2,3)(x)$

In the presence of electromagnetic potential, the parity dual of massless particles may differ, e.g., just static electric $σ^i ∂_i ϕ ± #i V ϕ = 0$ 

When electromagnetic potential = 0, the parity dual eq is the same.